config/routes.rb
Rails.application.routes.draw do
  root to: "clients#index"
  devise_for :users, only: :sessions
  resources :products
  resources :clients
  resources :invoices

  match "/404", to: "application#not_found", via: :all
  match "/500", to: "application#internal_server_error", via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :invoices, dependent: :destroy
  has_many :invoice_details, through: :invoices
  has_many :products, through: :invoice_details

  validates :name, presence: true
  validates :address, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: Settings.validations.email_regex }
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :client

  has_many :invoice_details, dependent: :destroy
  has_many :products, through: :invoice_details

  accepts_nested_attributes_for :invoice_details, allow_destroy: true

  def product_count
    invoice_details.sum(&:quantity)
  end

  def total_price
    invoice_details.reduce(0) { |sum, invoice_detail| sum + invoice_detail.total_price }
  end
end

app/models/invoice_detail.rb
class InvoiceDetail < ApplicationRecord
  belongs_to :invoice
  belongs_to :product, -> { with_deleted }

  validates :quantity, presence: true

  delegate :name, :unit, to: :product, prefix: true

  after_create :set_price

  def total_price
    (price || 0) * (quantity || 0)
  end

  private

  def set_price
    self.price = product.price
    save!
  end
end

app/models/product.rb
class Product < ApplicationRecord
  acts_as_paranoid
  paginates_per 20

  has_many :invoice_details
  has_many :invoices, through: :invoice_details
  has_many :clients, -> { distinct }, through: :invoices
end

app/models/settings.rb
class Settings < Settingslogic
  source Rails.root.join("config", "settings.yml")
  namespace Rails.env
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :validatable

  validates :email, presence: true, uniqueness: true, format: { with: Settings.validations.email_regex }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ErrorHandlerConcern

  before_action :authenticate_user!

  layout :layout

  private

  def layout
    is_a?(Devise::SessionsController) ? "sign_in" : "application"
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  respond_to :html

  before_action :load_client, only: %i(show edit update destroy)

  def index
    @clients = Client.all.page(params[:page])
  end

  def show
    @invoices = @client.invoices.page(params[:page])
    @invoice = Invoice.new(invoice_details: [InvoiceDetail.new])
    @products = Product.all
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      flash[:notice] = "Created"
      respond_with :edit, @client
    else
      flash[:error] = @client.errors.full_messages.uniq.join(", ")
      respond_with :new, :client
    end
  end

  def edit
  end

  def update
    if @client.update(client_params)
      flash[:notice] = "Updated"
      respond_with :edit, @client
    else
      flash[:error] = @client.errors.full_messages.uniq.join(", ")
      respond_with :edit, @client
    end
  end

  def destroy
    if @client.destroy
      flash[:notice] = "Deleted"
    else
      flash[:error] = "Can not delete"
    end
    redirect_to clients_path
  end

  private

  def client_params
    params.require(:client).permit(:name, :email, :address, :phone)
  end

  def load_client
    @client = Client.find(params[:id])
  end
end

app/controllers/concerns/error_handler_concern.rb
module ErrorHandlerConcern
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::UnknownAttributeError, ActiveRecord::StatementInvalid, ActiveRecord::RecordInvalid do
      render_error 500
    end

    rescue_from ActiveRecord::RecordNotFound do
      render_error 404
    end

    def not_found
      render_error 404
    end

    def internal_server_error
      render_error 500
    end

    private

    def render_error(code)
      render file: Rails.root.join("public", "#{code}.html"), layout: false
    end
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :load_invoice, only: %i(show edit update destroy)

  def show
    @invoice_details = @invoice.invoice_details
  end

  def edit
    @products = Product.all
  end

  def create
    if Invoice.create(invoice_params)
      flash[:notice] = "Created"
    else
      flash[:error] = "Can not create"
    end
    redirect_to client_path(invoice_params[:client_id])
  end

  def destroy
    if @invoice.destroy
      flash[:notice] = "Deleted"
    else
      flash[:error] = "Can not detele"
    end
    redirect_to client_path(@invoice.client_id)
  end

  def update
    @invoice.update!(invoice_params)
    redirect_to client_path(@invoice.client_id), flash: { notice: "Updated" }
  end

  private

  def load_invoice
    @invoice = Invoice.find(params[:id])
  end

  def invoice_params
    params.require(:invoice).permit(:client_id, invoice_details_params)
  end

  def invoice_details_params
    { invoice_details_attributes: [:product_id, :quantity] }.tap do |attr|
      attr[:invoice_details_attributes].push(:id, :_destroy) if @invoice&.persisted?
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  respond_to :html

  before_action :load_product, only: %i(show edit update destroy)

  def index
    @products = Product.all.page(params[:page])
  end

  def show
    @clients = @product.clients.page(params[:page])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Created"
      respond_with :edit, @product
    else
      flash[:error] = @product.errors.full_messages.uniq.join(", ")
      respond_with :new, :product
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      flash[:notice] = "Updated"
      respond_with :edit, @product
    else
      flash[:error] = @product.errors.full_messages.uniq.join(", ")
      respond_with :edit, @product
    end
  end

  def destroy
    if @product.destroy
      flash[:notice] = "Deleted"
    else
      flash[:error] = "Can not delete"
    end
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :unit, :price, :description)
  end

  def load_product
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert--danger alert--dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>
       #{pluralize(resource.errors.count, "error")} must be fixed
      </strong>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/form_helper.rb
module FormHelper
  def link_to_add_row(name, f, association, **args)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render("#{association}/form", f: builder)
    end
    link_to(name, "#", class: "add_nested_fields " + args[:class], data: { id: id, fields: fields.gsub("\n", "") })
  end
end

app/views/clients/_client.html.erb
<tr>
  <td><%= client.name %></td>
  <td><%= client.email %></td>
  <td><%= client.address %></td>
  <% if action %>
    <td class="text-right">
      <%= link_to client_path(client), class: "btn btn-info btn-xs" do %>
        <i class="fas fa-eye"></i>
      <% end %>
      <%= link_to edit_client_path(client), class: "btn btn-default btn-xs" do %>
        <i class="fas fa-edit"></i>
      <% end %>
      <%= link_to client_path(client), class: "btn btn-danger btn-xs", method: :delete do %>
        <i class="fas fa-trash"></i>
      <% end %>
    </td>
  <% end %>
</tr>

app/views/clients/_clients.html.erb
<table class="table table--default table-responsive table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Address</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render clients, action: action %>
  </tbody>
</table>
<%= paginate clients %>

app/views/clients/_form.html.erb
<div class="form-group">
  <%= f.label "Name" %>
  <%= f.text_field :name, class: "form-control", placeholder: "Name of client", required: true %>
  <span class="help-block"><i>* Require</i><span>
</div>

<div class="form-group">
  <%= f.label "Email" %>
  <%= f.email_field :email, class: "form-control", placeholder: "email@email.com", required: true %>
  <span class="help-block"><i>* Require</i><span>
</div>


<div class="form-group">
  <%= f.label "Address" %>
  <%= f.text_field :address, placeholder: "Address here", class: "form-control", required: true %>
  <span class="help-block"><i>* Require</i><span>
</div>

app/views/clients/edit.html.erb
<div class="panel panel-default panel--light panel--md">
  <div class="panel-heading">
    <h3 class="panel-title">Edit client</h3>
  </div>
  <div class="panel-body">
    <%= form_for @client, url: client_path(@client), role: :form do |f| %>
      <div class="box">
        <div class="box-body">
          <%= render partial: 'form', locals: { f: f } %>
        </div>

        <div class="box-footer">
          <%= link_to 'Cancel', clients_path, class: 'btn btn-danger' %>
          <%= f.submit 'Update', class: "btn btn-success" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/clients/index.html.erb
<div class="panel panel-default panel--light">
  <div class="panel-heading">
    <h4 class="panel-title">Client list</h3>
    <%= link_to new_client_path, class: "btn btn-success btn-xl" do %>
      <i class="fas fa-plus-circle"></i>
    <% end %>
  </div>
  <div class="panel-body">
    <%= render partial: "clients",  locals: { clients: @clients, action: true } %>
  </div>
</div>

app/views/clients/new.html.erb
<div class="panel panel-default panel--light panel--md">
  <div class="panel-heading">
    <h3 class="panel-title">Create new client</h3>
  </div>
  <div class="panel-body">
    <%= form_for @client, url: clients_path, role: :form do |f| %>
      <div class="box">
        <div class="box-body">
          <%= render partial: 'form', locals: { f: f } %>
        </div>
        <div class="box-footer">
          <%= link_to 'Cancel', clients_path, class: 'btn btn-danger' %>
          <%= f.submit 'Add', class: "btn btn-success" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/clients/show.html.erb
<div class="row">
  <div class="col-lg-4">
    <div class="panel panel-default panel--light">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @client.name %></h3>
      </div>
      <div class="panel-body">
        <div class="client-info">
          <h4><span class="label label-default">Information</span></h4>
          <div class="well">
            <div class="row">
              <div class="col-xs-3"><b>Email:</b></div>
              <div class="col-xs-9"><%= @client.email %></div>
              <div class="col-xs-3"><b>Address:</b></div>
              <div class="col-xs-9"><%= @client.address %></div>
            </div>
          </div>
        </div>
        <hr>
        <div class="new-invoce">
          <h4><span class="label label-primary">Add invoice</span></h4>
          <%= form_for @invoice, url: invoices_path, role: :form, class: "form-horizontal" do |f| %>
            <div class="box">
              <div class="box-body invoice-details-list">
                <%= render partial: 'invoices/form', locals: { f: f, client: @client } %>
              </div>

              <div class="box-footer text-right col-xs-12">
                <%= link_to 'Cancel', client_path(@client), class: 'btn btn-danger' %>
                <%= f.submit 'Add', class: "btn btn-success" %>
              </div>

            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-8">
    <div class="panel panel-default panel--light">
      <div class="panel-heading">
        <h3 class="panel-title">Invoice List</h3>
      </div>
      <div class="panel-body">
        <%= render partial: "invoices/invoices",  locals: { invoices: @invoices } %>
      </div>
    </div>
  </div>
</div>

app/views/invoice_details/_form.html.erb
<div class="form form--info">
  <button type="button" class="close remove_nested_fields"><span aria-hidden="true">&times;</span></button>
  <div class="nested_field_element">
    <div class="form-group ">
      <%= f.hidden_field :_destroy, value: 0, id: "_destroy" %>
      <%= f.label "Product" %>
      <%= f.select :product_id, @products.collect { |p| [p.name, p.id] }, { selected: f.object.product_id }, { class: "form-control" } %>
      <span class="help-block"><i>* Require</i><span>
    </div>

    <div>
      <%= f.label "Quantity" %>
      <%= f.number_field :quantity, class: "form-control", placeholder: "12", required: true %>
      <span class="help-block"><i>* Require</i><span>
    </div>
  </div>
</div>

app/views/invoice_details/_invoice_detail.html.erb
<tr>
  <td><%= invoice_detail.id %></td>
  <td><%= invoice_detail.product_name %></td>
  <td><%= invoice_detail.price %></td>
  <td><%= invoice_detail.product_unit %></td>
  <td><%= invoice_detail.quantity %></td>
  <td><%= invoice_detail.total_price %></td>
</tr>

app/views/invoice_details/_invoice_details.html.erb
<table class="table table--default table-responsive table-hover">
  <thead>
    <tr>
      <th>Id</th>
      <th>Product</th>
      <th>Price</th>
      <th>Unit</th>
      <th>Quantity</th>
      <th>Total price</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render invoice_details %>
    <tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>Total: </td>
    <td><%= invoice.total_price %></td>
  </tr>
  </tbody>

</table>

app/views/invoices/_form.html.erb
<%= f.hidden_field :client_id, value: @client&.id || f.object.client_id %>
<div class= "nested_fields">
    <%= f.fields_for :invoice_details do |ff| %>
      <%= render partial: "invoice_details/form", locals: { f: ff } %>
    <% end %>
</div>
<%= link_to_add_row('Add Product', f, :invoice_details, class: 'btn btn-info') %>

app/views/invoices/_invoice.html.erb
<tr>
  <td><%= invoice.id %></td>
  <td><%= invoice.product_count %></td>
  <td><%= invoice.total_price %></td>
  <td><%= invoice.created_at %></td>
  <td class="text-right">
    <%= link_to invoice_path(invoice), class: "btn btn-info btn-xs" do %>
      <i class="fas fa-eye"></i>
    <% end %>
    <%= link_to edit_invoice_path(invoice), class: "btn btn-default btn-xs" do %>
      <i class="fas fa-edit"></i>
    <% end %>
    <%= link_to invoice_path(invoice), class: "btn btn-danger btn-xs", method: :delete do %>
      <i class="fas fa-trash"></i>
    <% end %>
  </td>
</tr>

app/views/invoices/_invoices.html.erb
<table class="table table--default table-responsive table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Product count</th>
      <th>Total price</th>
      <th>Created at</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render invoices %>
  </tbody>
</table>
<%= paginate invoices %>

app/views/invoices/edit.html.erb
<div class="panel panel-default panel--light panel--md">
  <div class="panel-heading">
    <h4 class="panel-title">Edit invoice</h3>
  </div>
  <div class="panel-body">
    <%= form_for @invoice, url: invoice_path(@invoice), role: :form do |f| %>
      <div class="box">
        <div class="box-body">
          <%= render partial: 'form', locals: { f: f } %>
        </div>

        <div class="box-footer text-center">
          <%= link_to 'Cancel', client_path(@invoice.client_id), class: 'btn btn-danger' %>
          <%= f.submit 'Update', class: "btn btn-success" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/invoices/show.html.erb
<div class="panel panel-default panel--light">
  <div class="panel-heading">
    <h3 class="panel-title">Invoice detail</h3>
  </div>
  <div class="panel-body">
    <%= render partial: "invoice_details/invoice_details",  locals: { invoice_details: @invoice_details, invoice: @invoice } %>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="header-wrapper">
  <div class="header">
    <div class="header__logo-wrapper">
      <h4>BrazilianCloud</h4>
    </div>
    <div class="header__left-nav">
      <div class="toggle-side-menu" onclick="toggleSideMenu()">
        <i class="fas fa-bars"></i>
      </div>
    </div>
    <ul class="header__right-nav">
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    </ul>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<div class="sidebar-wrapper">
  <div class="sidebar">
    <ul class="sidebar__menu menu">
      <!--  Sigle menu item  -->
      <li class="menu__item menu__item--active">
        <%= link_to products_path do %>
          <i class="fas fa-book"></i>
          <span class="menu__text">Products</span>
        <% end%>
      </li>
      <li class="menu__item">
        <%= link_to clients_path do %>
          <i class="fas fa-users"></i>
          <span class="menu__text">Client</span>
        <% end%>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrazilianCloud</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/header" %>
    <div class="d-flex" id="app">
      <%= render partial: "layouts/sidebar" %>
      <div class="page-container-wrapper">
        <%= render "shared/alert"%>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/sign_in.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BrazilianCloud</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/alert"%>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<div class="form-group">
  <%= f.label "Name" %>
  <%= f.text_field :name, class: "form-control", placeholder: "Name of product", required: true %>
  <span class="help-block"><i>* Require</i><span>
</div>

<div class="form-group">
  <%= f.label "Unit" %>
  <%= f.text_field :unit, class: "form-control", placeholder: "Giga", required: true %>
  <span class="help-block"><i>* Require</i><span>
</div>


<div class="form-group">
  <%= f.label "Price" %>
  <%= f.number_field :price, placeholder: "500", class: "form-control" %>
  <span class="help-block"><i>* Require</i><span>
</div>

<div class="form-group">
  <%= f.label "Descripton" %>
  <%= f.text_area :description, class: "form-control", require: true %>
</div>

app/views/products/_product.html.erb
<tr>
  <td><%= product.name %></td>
  <td><%= product.unit %></td>
  <td><%= product.price %></td>
  <td><%= product.description %></td>
  <td class="text-right">
    <%= link_to product_path(product), class: "btn btn-info btn-xs" do %>
      <i class="fas fa-eye"></i>
    <% end %>
    <%= link_to edit_product_path(product), class: "btn btn-default btn-xs" do %>
      <i class="fas fa-edit"></i>
    <% end %>
    <%= link_to product_path(product), class: "btn btn-danger btn-xs", method: :delete do %>
      <i class="fas fa-trash"></i>
    <% end %>
  </td>
</tr>

app/views/products/_products.html.erb
<table class="table table--default table-responsive table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Unit</th>
      <th>Price</th>
      <th>description</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render products %>
  </tbody>
</table>
<%= paginate @products %>

app/views/products/edit.html.erb
<div class="panel panel-default panel--light">
  <div class="panel-heading">
    <h4 class="panel-title">Edit product</h3>
  </div>
  <div class="panel-body">
    <%= form_for @product, url: product_path(@product), role: :form do |f| %>
      <div class="row">
        <div class="col-xs-4">
          <div class="box">
            <div class="box-body">
              <%= render partial: 'form', locals: { f: f } %>
            </div>

            <div class="box-footer">
              <%= link_to 'Cancel', products_path, class: 'btn btn-danger' %>
              <%= f.submit 'Update', class: "btn btn-success" %>
            </div>

          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/index.html.erb
<div class="panel panel-default panel--light">
  <div class="panel-heading">
    <h4 class="panel-title">Product list</h3>
    <%= link_to new_product_path, class: "btn btn-success btn-xl" do %>
      <i class="fas fa-plus-circle"></i>
    <% end %>
  </div>
  <div class="panel-body">
    <%= render partial: "products",  locals: { products: @products } %>
  </div>
</div>

app/views/products/new.html.erb
<div class="panel panel-default panel--light panel--md">
  <div class="panel-heading">
    <h3 class="panel-title">Create new product</h3>
  </div>
  <div class="panel-body">
    <%= form_for @product, url: products_path, role: :form do |f| %>
      <div class="box">
        <div class="box-body">
          <%= render partial: 'form', locals: { f: f } %>
        </div>

        <div class="box-footer text-center">
          <%= link_to 'Cancel', products_path, class: 'btn btn-danger' %>
          <%= f.submit 'Add', class: "btn btn-success" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<div class="panel panel-default panel--light">
  <div class="panel-heading">
    <h3 class="panel-title"><%= @product.name %></h3>
  </div>
  <div class="panel-body">
    <h3>Client using list</h3>
    <%= render partial: "clients/clients",  locals: { clients: @clients, action: false } %>
  </div>
</div>

app/views/shared/_alert.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert--<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li class="align-self-center">
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>